name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets[format('AZURE_CLIENT_ID_%s', github.event.inputs.environment | upper)] }}
      ARM_CLIENT_SECRET: ${{ secrets[format('AZURE_CLIENT_SECRET_%s', github.event.inputs.environment | upper)] }}
      ARM_SUBSCRIPTION_ID: ${{ secrets[format('AZURE_SUBSCRIPTION_ID_%s', github.event.inputs.environment | upper)] }}
      ARM_TENANT_ID: ${{ secrets[format('AZURE_TENANT_ID_%s', github.event.inputs.environment | upper)] }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        run: |
          ENV=${{ github.event.inputs.environment }}
          terraform init \
            -backend-config=environments/backend.tfvars \
            -backend-config="key=vm-${ENV}.tfstate" \
            -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          ENV=${{ github.event.inputs.environment }}
          terraform plan -var-file=environments/${ENV}.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
